apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  labels:
    app: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000