apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-waf
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
        app.kubernetes.io/name: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
      - name: docker-secret  # 컨테이너 레지스트리 접근을 위한 Secret 설정
      containers:
      - image: YOUR_REGISRTY:npic-waf-3.7.0 # NGINX Plus Ingress Controller 이미지 설정
        imagePullPolicy: IfNotPresent
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: readiness-port
          containerPort: 8081
        - name: prometheus
          containerPort: 9113
        - name: service-insight
          containerPort: 9114
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 101 #nginx
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -enable-app-protect
        volumeMounts:
        - name: app-protect-bd-config
          mountPath: /opt/app_protect/bd_config
        - name: app-protect-config
          mountPath: /opt/app_protect/config
        - name: app-protect-bundles
          mountPath: /etc/app_protect/bundles
      - name: waf-enforcer
        image: YOUR_REGISRTY:waf-enforcer-5.3.0 # NGINX App Protect WAF enforcer 이미지 설정
        imagePullPolicy: IfNotPresent
        env:
          - name: ENFORCER_PORT
            value: "50000"
        volumeMounts:
          - name: app-protect-bd-config
            mountPath: /opt/app_protect/bd_config
      - name: waf-config-mgr
        image: YOUR_REGISRTY:waf-config-mgr-5.3.0 # NGINX App Protect WAF config-mgr 이미지 설정
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        volumeMounts:
        - name: app-protect-bd-config
          mountPath: /opt/app_protect/bd_config
        - name: app-protect-config
          mountPath: /opt/app_protect/config
        - name: app-protect-bundles
          mountPath: /etc/app_protect/bundles
      volumes:
      - name: app-protect-bd-config
        persistentVolumeClaim:
          claimName: waf-bd-conf-pvc
      - name: app-protect-config
        persistentVolumeClaim:
          claimName: waf-conf-pvc
      - name: app-protect-bundles
        persistentVolumeClaim:
          claimName: waf-bundle-pvc